services:
  vector_store:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./mlruns:/mlruns